# Site settings
title: SoNerdy
email: brandon@sonerdy.com
description: "Technology blog &amp; consulting company - SoNerdy LLC"
baseurl: ""
url: "http://sonerdy.com"

# Build settings
markdown: kramdown
permalink: pretty
